- roles/amq_broker/README.md
- roles/amq_broker/defaults/main.yml
- roles/amq_broker/meta/argument_specs.yml
- roles/amq_broker/tasks/configure.yml
- roles/amq_broker/tasks/prereqs.yml
- roles/amq_broker/tasks/systemd.yml
- roles/amq_broker/templates/amq_broker.service.j2
These tasks build options to pass to `artemis create` command
> Import artemis create configuration tasks

- galaxy.yml
Ignore .gitignore file from collection
> Ignore .gitignore file from collection

- roles/activemq/tasks/configure_broker.yml
> Add steps to determine metrics plugin filename

- .ansible-lint
- .github/workflows/ci.yml
- molecule/amq_upgrade/molecule.yml
- molecule/amq_upgrade/requirements.yml
- molecule/default/molecule.yml
- molecule/requirements.yml
- molecule/static_cluster/molecule.yml
- molecule/static_cluster/requirements.yml
- roles/activemq/tasks/main.yml
- roles/activemq/templates/amq_broker.service.j2
> Restore wait_for_log string in live-only ha

- plugins/filter/pbkdf2_hmac.py
- plugins/filter/pbkdf2_hmac.yml
- roles/activemq/defaults/main.yml
- roles/activemq/meta/argument_specs.yml
- roles/activemq/tasks/configure_broker.yml
- roles/activemq/tasks/install.yml
- roles/activemq/tasks/main.yml
- roles/activemq/templates/amq_broker.service.j2
- roles/activemq/templates/amq_broker.sysconfig.j2
- roles/activemq/templates/log4j2.properties.j2
> Update logging facade config (by activemq version)

- molecule/amq_upgrade/verify.yml
- molecule/custom_xml/verify.yml
- molecule/default/molecule.yml
- molecule/default/verify.yml
- molecule/mask_passwords/verify.yml
- molecule/static_cluster/verify.yml
- roles/activemq/README.md
- roles/activemq/defaults/main.yml
- roles/activemq/files/artemis-configuration-2.32.xsd
- roles/activemq/meta/argument_specs.yml
- roles/activemq/meta/main.yml
The default molecule scenario now executes on RHEL 9.
> Update activemq default to 2.32 / amq_broker to 7.11.6

- README.md
- meta/runtime.yml
- roles/activemq/meta/main.yml
ansible-core went EOL on May 31st
> Set minimum ansible-core version to >=2.15

- molecule/default/converge.yml
- roles/activemq/templates/addresses.broker.xml.j2
Test scenario provided under default molecule setup.
Fix #128
> Fix configuration of multicast addresses/queues

- roles/activemq/defaults/main.yml
- roles/activemq/meta/argument_specs.yml
- roles/activemq/tasks/configure_broker.yml
- roles/activemq/tasks/federations.yml
- roles/activemq/tasks/validate_config.yml
- roles/activemq/templates/federations.broker.xml.j2
reference: https://github.com/ansible-middleware/amq/issues/134
```yaml
activemq_federations:
- name: us-east-1
user: foo
password: bar
protocol: CORE
upstreams:
- name: foo-upstream
static_connectors:
- node_foo
- node_bar
policies:
- policy_set_foo
parameters:
ha: "true"
circuit-breaker-timeout: 100000
- name: bar-upstream
discovery_group: disco
policies:
- policy_set_bar
downstreams:
- name: downstream_baz
upstream_connector_ref: up-con
static_connectors:
- node_baz1
- node_baz2
parameters:
connection_ttl: 50000
policies:
- policy_set_foo
- policy_set_bar
- name: secured_foo
user: foo-club
password: dontsayit
upstream_connector_ref: up-con-sec
discovery_group: foo
parameters:
connection_ttl: 50000
policies:
- policy_set_foo
- policy_set_bar
policy_sets:
- name: policy_set_foo
policies: …
```
> Federated addressing

- CONTRIBUTING.md
- README.md
- docs/index.rst
- docs/static_cluster.md
- docs/testing.md
- roles/activemq/tasks/install.yml
- roles/activemq/tasks/main.yml
Add a guide for HA
Closes #102
> docs: add primary/backup guide

- docs/base_deployment.md
- docs/index.rst
- docs/static_cluster.md
Add a guide to the docs that shows basic install, version update, and address config
> docs: add base deployment guide

- molecule/amq_upgrade/converge.yml
- molecule/amq_upgrade/prepare.yml
- roles/activemq/files/artemis-configuration-2.36.xsd
- roles/activemq/tasks/configure_files.yml
- roles/activemq/tasks/upgrade.yml
Web console access is set during very first installation by artemis create. If it is changed afterwards, bootstrap.xml is not update to repleft the changes.
> Update jolokia access when bind host and port are changed

- roles/activemq/tasks/prereqs.yml
> ensure targets use supported OS family

- .github/workflows/traffic.yml
- CHANGELOG.rst
- docs/_gh_include/footer.inc
- docs/index.rst
- roles/activemq/handlers/main.yml
> Force `activemq_configuration_file_refresh_period` integer type in handler

- molecule/live_only/converge.yml
- molecule/mask_passwords/converge.yml
- molecule/mask_passwords/prepare.yml
- molecule/mask_passwords/templates/logging/custom.log4j2.properties.j2
- molecule/mirroring/converge.yml
- molecule/replication/converge.yml
- molecule/static_cluster/converge.yml
- roles/activemq/tasks/systemd.yml
- roles/activemq/templates/log4j2.properties.j2
- roles/activemq/templates/logging.properties.j2
Issue: https://github.com/ansible-middleware/amq/issues/206
> Store the log files on a separate partition compared to the base of the amq file system

- .github/workflows/ci.yml
- README.md
- molecule/amq_upgrade/verify.yml
- molecule/custom_xml/verify.yml
- molecule/default/verify.yml
- molecule/mask_passwords/verify.yml
- molecule/uninstall/verify.yml
- roles/activemq/tasks/broker_plugins.yml
- roles/activemq/tasks/configure_broker.yml
- roles/activemq/tasks/firewalld.yml
- roles/activemq/tasks/jgroups.yml
- roles/activemq/tasks/start.yml
- roles/activemq/tasks/systemd.yml
- roles/activemq/tasks/upgrade.yml
- roles/activemq_uninstall/tasks/systemd.yml
- roles/activemq_uninstall/tasks/uninstall.yml
Issue: https://issues.redhat.com/browse/AMW-374
> AMW-374 amq collection GitHub action molecule pipelines are breaking because of sudo permission issue

- molecule/amq_upgrade/verify.yml
- molecule/custom_xml/verify.yml
- molecule/default/verify.yml
- molecule/live_only/converge.yml
- molecule/mask_passwords/verify.yml
- molecule/mirroring/converge.yml
- molecule/replication/converge.yml
- molecule/static_cluster/converge.yml
- molecule/uninstall/verify.yml
- roles/activemq/tasks/broker_plugins.yml
- roles/activemq/tasks/configure_broker.yml
- roles/activemq/tasks/firewalld.yml
- roles/activemq/tasks/jgroups.yml
- roles/activemq/tasks/start.yml
- roles/activemq/tasks/stop.yml
- roles/activemq/tasks/systemd.yml
- roles/activemq/tasks/upgrade.yml
- roles/activemq_uninstall/tasks/systemd.yml
- roles/activemq_uninstall/tasks/uninstall.yml
Issue: https://issues.redhat.com/browse/AMW-373
GitHub Issue: https://github.com/ansible-middleware/amq/issues/212
> AMW-373 amq collection should stop services before upgrade

- molecule/mask_passwords/prepare.yml
- roles/activemq/tasks/systemd.yml
- roles/activemq/templates/amq_broker.service.j2
Issue: https://github.com/ansible-middleware/amq/issues/206#issuecomment-2862478626
> Fix systemd configuration when absolute logfile paths are used

- roles/activemq/tasks/acceptors.yml
- roles/activemq/tasks/configure_artemis.yml
- roles/activemq/tasks/mask_password.yml
- roles/activemq/tasks/validate_config.yml
Issue: https://issues.redhat.com/browse/AMW-397
GitHub Issue: https://github.com/ansible-middleware/amq/issues/99
> Allow to avoid `no_log` when running playbooks in check mode

- roles/activemq/tasks/user_roles.yml
Issue: https://issues.redhat.com/browse/AMW-408
> AMW-408 Error XMLSchemaParseError with Ansible collection 2.3.2 for AMQ 7.13
