roles/amq_broker/README.md
roles/amq_broker/defaults/main.yml
roles/amq_broker/meta/argument_specs.yml
roles/amq_broker/tasks/configure.yml
roles/amq_broker/tasks/systemd.yml
roles/amq_broker/templates/logging.properties.j2

New variables:
|`amq_broker_enable_audit`| Whether to enable audit file logging | `False` |
|`amq_broker_logger_level`| Root logging level | `INFO` |
|`amq_broker_logger_core_server_level`| Logging level for org.apache.activemq.artemis.core.server | `INFO` |
|`amq_broker_logger_journal_level`| Logging level for org.apache.activemq.artemis.journal | `INFO` |
|`amq_broker_logger_utils_level`| Logging level for org.apache.activemq.artemis.utils | `INFO` |
|`amq_broker_logger_utils_critical_level`| Logging level for org.apache.activemq.artemis.utils.critical | `INFO` |
|`amq_broker_logger_jms_level`| Logging level for org.apache.activemq.artemis.jms | `INFO` |
|`amq_broker_logger_integration_bootstrap_level`| Logging …

Add vars and template for logging configuration

---

molecule/amq_upgrade/verify.yml
roles/amq_broker/README.md
roles/amq_broker/defaults/main.yml
roles/amq_broker/meta/argument_specs.yml
roles/amq_broker/tasks/install.yml

New variable `activemq_local_archive_repository` configures a directory accessible from controller to use for downloading/installing provided install archives. Default is `ansible-playbook` command `$PWD` (as previously set) so no change is necessary if the config is not used.

Variable to config controller download/offline directory

---

molecule/amq_upgrade/converge.yml
molecule/default/converge.yml
roles/amq_broker/defaults/main.yml
roles/amq_broker/meta/argument_specs.yml
roles/amq_broker/tasks/mask_password.yml
roles/amq_broker/tasks/user_roles.yml
roles/amq_broker/templates/artemis-roles.properties.j2
roles/amq_broker/templates/security_settings.broker.xml.j2

Fix #12 
Fix #16 
While this changeset originates from a bug report, the solution involves refactoring the key in the `activemq_users` dictionary from `role: str` to `roles: list(str)`, thus it is marked as major_change

Allow to list roles for users, specify security setting match address

---

.ansible-lint
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/systemd.yml
roles/activemq/templates/amq_broker.service.j2

Fix #35 
This change adds `RequiresMountsFor=` to the systemd unit when shared storage is used (activemq_shared_storage=True). A new variable `activemq_shared_storage_mounted` (default True), allows to avoid this behaviour (ie. the shared file system is local, instances are colocated).
As an alternative it is also now possible to override the systemd configuration with a custom template, to be passed-in via the new variable `activemq_service_override_template` (default: ''). The file pointed by the filename should be made available in the ansible playbook template lookup directories.
|`activemq_shared_storage_mounted`| Whether the systemd unit must require a mounted path (only when using shared storage) | `True` | …

Add systemd RequiresMountsFor and unit custom template

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/address_settings.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/connectors.yml
roles/activemq/templates/address_settings.broker.xml.j2
roles/activemq/templates/cluster_connections.broker.xml.j2

* Address settings
|`activemq_address_settings`| Address settings configuration; list of `{ match address string and parameters }` | Generate same configuration as `artemis create` |
Sample address settings:
```
- match: activemq.management#
dead_letter_address: DLQ
expiry_address: ExpiryQueue
redelivery_delay: 0
max_size_bytes: -1
message_counter_history_day_limit: 10
address_full_policy: PAGE
auto_create_queues: true
auto_create_addresses: true
auto_create_jms_queues: true
auto_create_jms_topics: true
```

Add configuration variables for address settings

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/prereqs.yml
roles/activemq/tasks/restart.yml
roles/activemq/tasks/start.yml
roles/activemq/templates/amq_broker.service.j2

The new variable, enabled by default when ha is enabled, adds a configuration to the systemd unit so that service start/restart commands return only after ports are open / console log line 
|`activemq_systemd_wait_for_port` | Whether systemd unit should wait for `activemq_port` before returning | `True` when activemq_ha_enabled is `True` and activemq_shared_storage is `False` |
|`activemq_systemd_wait_for_log` | Whether systemd unit should wait for service to be up in logs | `True` when activemq_ha_enabled and activemq_shared_storage are `True` |

New flags make systemd unit wait for activemq ports or logs

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/addresses.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/templates/addresses.broker.xml.j2
roles/activemq/templates/jolokia-access.xml.j2

* Addresses configuration
|`activemq_addresses`| Addresses/queue configuration; list of `{ name, [anycast\|multicast], and parameters }` | Generate same configuration as `artemis create` |
Sample addresses:
```
- name: ExpiryQueue
anycast:
- name: ExpiryQueue
- name: Virtual
anycast:
- name: Virtual
filter: 'discard="true"'
max_consumers: 5
consumers_before_dispatch: 1
```

Add address/queue configuration

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/diverts.yml
roles/activemq/templates/diverts.broker.xml.j2

* Diverts configuration
|`activemq_diverts`| Diverts configuration; list of `{ name with parameters }` | `[]` |
Sample divert:
```
- name: SAMPLEDIVERT
address: FROMQUEUE
forwarding-address: TOQUEUE
routing-type: ANYCAST
filter: "msgType LIKE '%ff%'"
exclusive: True
```

Add diverts configuration

---

galaxy.yml

Change was part of #51 
|`activemq_cors_allow_origin`| List of CORS allow origin setting for jolokia | `[ *://0.0.0.0* ]` |
Playbooks setting activemq_cors_allow_origin on <= 1.2.0 version need to have the variable redefined as a list

Type for `activemq_cors_allow_origin` changed from string to list of strings

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/handlers/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/address_settings.yml
roles/activemq/tasks/addresses.yml
roles/activemq/tasks/diverts.yml
roles/activemq/tasks/journal.yml
roles/activemq/tasks/user_roles.yml

The system will perform a periodic check on the configuration files, configured by configuration-file-refresh-period, with the default at 5000, in milliseconds. These checks can be disabled by specifying -1.
A new variable, `activemq_configuration_file_refresh_period` (same default), allows to set or disable configuration auto-refresh:
|`activemq_configuration_file_refresh_period`| Periodic refresh of configuration in milliseconds; can be disabled by specifying -1 | `5000` |
When auto-refresh is enabled, changes to:
* Address Settings
* Security Settings
* Diverts
* Addresses & Queues
* Bridges
should NOT trigger service restart, delegating the reload to the configuration auto-refresh feature.

Don't trigger restarts when config auto-refresh is enabled

---

.ansible-lint
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml

Fix #56 
A new variable is introduced, so that interpolation between the default data directory path and the data directory when shared storage is enabled is possible:
|`activemq_data_directory`| The activemq data directory path | `data/`, or the value of `activemq_shared_storage_path` if activemq_shared_storage is set |

Add `activemq_data_directory` variable

---

.ansible-lint
.gitignore
README.md
plugins/modules/xml.py
requirements.txt
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/install.yml
roles/activemq/tasks/main.yml
roles/activemq/tasks/prereqs.yml
roles/activemq/tasks/validate_config.yml
roles/activemq/templates/address_settings.broker.xml.j2
roles/activemq/vars/main.yml

Fix #55 
Ideally `active_address_settings` items should accept a map of arbitrary activemq settings (in snake-case instead of kebab-case); given a specific activemq version, the generated configuration should be validate against the corresponding xsd, possibly in the prereq phase. An additional variable `activemq_address_settings_defaults` should control the output (or not) of passed-in parameters that are defined as default in the xml schema, in order to explicitly fix a configuration between schema updates, or alternatively accept  whatever is the default of that version.
This PR adds extra tasks before the install/configuration phase, which take care of fetching the xsd schemas for required activemq version, pre-generate the configuration, and perform a schema validation step against …

Configuration pre-install validation against schema

---

README.md
galaxy.yml
molecule/amq_upgrade/converge.yml
molecule/amq_upgrade/prepare.yml
molecule/amq_upgrade/requirements.yml
molecule/default/converge.yml
molecule/default/requirements.yml
molecule/static_cluster/converge.yml
molecule/static_cluster/requirements.yml
playbooks/activemq.yml
playbooks/activemq_cluster.yml
requirements.yml
roles/activemq/README.md
roles/activemq/meta/argument_specs.yml
roles/activemq/meta/main.yml
roles/activemq/tasks/install.yml

Remove former implementation of Red Hat customer portal download and replace with new implementation provided by middleware_automation.common collection. This change only has impact on the downstream redhat.amq_broker collection.

Switch middleware_automation.redhat_csp_download for middleware_automation.common

---

molecule/default/converge.yml
roles/activemq/tasks/user_roles.yml
roles/activemq/tasks/validate_config.yml
roles/activemq/templates/security_settings.broker.xml.j2

Fix #64 
Having multiple role definitions for the same queue selector results in duplicate xml blocks with same match element

Avoid generating duplicated security-settings match elements

---

molecule/amq_upgrade/prepare.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/files/artemis-configuration-2.21.xsd
roles/activemq/files/artemis-configuration-7.11.xsd
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/broker_connections.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/prereqs.yml
roles/activemq/tasks/validate_config.yml
roles/activemq/templates/broker_connections.broker.xml.j2

Element broker-connections can now be configured with the variable:
|`activemq_broker_connections`| AMQP broker connections configuration<br>List of `{ name(str),uri(str),operations(list of dicts) }`<br>with operation `type` in  `[mirror,sender,receiver,peer]` | `[]` |
Sample of mirroring operation:
```
activemq_broker_connections:
- uri: 'tcp://<hostname>:<port>'
name: DC2
sync: true
operations:
- type: mirror
parameters:
queue-removal: false
```
Sample for sender-receiver operation:
```
activemq_broker_connections:
- uri: 'tcp://<hostname>:<port>'
name: other-server
operations:
- type: sender
parameters:
address-match: 'queues.#'
- type: receiver
parameters:
address-match: 'remotequeues.#'
```
Broker connections …

Provide AMQP broker-connections configuration

---

roles/activemq/tasks/install.yml

Fix the case when the root directory of the install zipfile is not the expected path (ie. amq_broker 7.11.0). Symlink the activemq user account home directory when this happens instead.
Fix #71

Handle case when install zipfile root is not expected

---

roles/activemq/tasks/install.yml
roles/activemq/templates/amq_broker.service.j2

Make the systemd unit for activemq use the `activemq_service_user` and `activemq_service_group`, instead of delegating the `artemis-service` script to do the switch
Second part fix for #75

Set systemd unit to run with `activemq_system_user` user

---

roles/activemq/tasks/systemd.yml

When `activemq_jvm_package` is used (default) and `activemq_java_home` is left empty (default), the JAVA_HOME path was determined inspecting the installed openjdk rpm. With this change it is now inferred from the jdk version and default alternatives paths.
Fix #81

Default java_home path uses alternatives

---

molecule/default/converge.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/install.yml
roles/activemq/templates/amq_broker.d.service.j2
roles/activemq/vars/main.yml

New variable:
|`activemq_service_user_home`| Service user home directory, defaults to artemis installation directory | `{{ activemq_dest }}/apache-artemis-{{ activemq_version }}` |
controls the path for the posix user that runs the service.
Fix #79

Allow to set arbitrary service user home_dir

---

roles/activemq/meta/argument_specs.yml
roles/activemq/vars/main.yml

With `redhat.amq_broker 1.3.7` it is necessary to override default of `amq_broker_logger_config_template` to `{{ 'log4j2.properties' if amq_broker_version is version_compare('7.11.0', '>=') else 'logging.properties' }}` (or just set the filename to 'log4j2.properties' or 'logging.properties' depending on the version). The problem is in the downstream parameters defined in argument specs.
Fix #85 
Workaround for bugzilla [#2224411](https://bugzilla.redhat.com/show_bug.cgi?id=2224411)

Fix incorrectly defined default for `amq_broker_logger_config_template`

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/journal.yml
roles/activemq/tasks/validate_config.yml
roles/activemq/tasks/validate_core_config.yml
roles/activemq/vars/main.yml

New parameters allow to set broker `global-max-size` and `global-max-bytes`:
|`activemq_global_max_messages`| Number of messages before all addresses will enter into their Full Policy configured. It works in conjunction with activemq_global_max_size, being whatever value hits its maximum first. | `-1` |
|`activemq_global_max_size` | Size (in bytes) before all addresses will enter into their Full Policy configured upon messages being produced. Supports byte notation like 'K', 'Mb', 'MiB', 'GB', etc. | `'-1'` |
Fix #88

Add parameters for `global-max-size` and `global-max-bytes`

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/log4j2.properties.j2

New parameters to control how many rolled log files to retain
|`activemq_logger_rollover_files`| Number of rollover log files | `5`|
|`activemq_logger_audit_rollover_files`| Number of rollover audit log files | `5` |
Fix #91

Add parameters to configure log4j2 rolling strategy

---

molecule/mask_passwords/converge.yml
molecule/mask_passwords/verify.yml
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/login.config.j2

The following new parameters allows to configure a secondary (sufficient) or primary (required) LDAP authentication endpoint.
|`activemq_auth_properties_enabled`| Whether to enable property based JAAS config | `True` |
|`activemq_auth_ldap_enabled` | Whether to enable LDAP based JAAS config" | `False` |
|`activemq_auth_ldap_url` | URL for LDAP server connection" | `ldap://localhost:389` |
|`activemq_auth_ldap_conn_username` | Bind username for LDAP server" | `uid=admin,ou=system` |
|`activemq_auth_ldap_conn_password` | Bind user password for LDAP server" | `password` |
|`activemq_auth_ldap_conn_codec` | Optional password codec class for bind user password" | `{{ activemq_password_codec }}` | …

Add ldap plugin configuration to JAAS login.config

---

roles/activemq/tasks/mask_password.yml

The command is used to create masked passwords both for the first time and to ensure idempotency. This change fixes the issue when using custom password codecs together with the prometheus metrics plugin
Fix #97

Ignore unwanted output from `artemis mask` command

---

roles/activemq/tasks/fastpackages.yml
roles/activemq/tasks/install.yml

Fix (workaround) #104 
The version to use is `amq_broker_version: 7.9.4` (no padding zeroes)

workaround metadata change in RHN download

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
roles/activemq/tasks/acceptors.yml
roles/activemq/tasks/address_settings.yml
roles/activemq/tasks/addresses.yml
roles/activemq/tasks/broker_connections.yml
roles/activemq/tasks/configure_artemis.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/connectors.yml
roles/activemq/tasks/diverts.yml
roles/activemq/tasks/fastpackages.yml
roles/activemq/tasks/firewalld.yml
roles/activemq/tasks/install.yml
roles/activemq/tasks/mask_password.yml
roles/activemq/tasks/prereqs.yml
roles/activemq/tasks/start.yml
roles/activemq/tasks/upgrade.yml
roles/activemq/tasks/validate_config.yml

General improvements to validation of controller download directory (`activemq_local_archive_repository`) and downloaded install archive for both cases of `activemq_offline_install`.
Fix #123

Improve validations for offline installs

---

molecule/static_cluster/converge.yml
molecule/static_cluster/molecule.yml
roles/activemq/README.md
roles/activemq/templates/amq_broker.service.j2
roles/activemq/templates/broker_connections.broker.xml.j2
roles/activemq/templates/ha_policy.xml.j2

This changeset tackles the linked issue, and update the configuration with connection username and password. 
|`activemq_broker_connections`| AMQP broker connections configuration; list of `{ name(str),uri(str),operations(list of dicts with type key in [mirror,sender,receiver,peer])) }` | `[]` |
Sample of mirroring operation:
```yaml
activemq_broker_connections:
- uri: 'tcp://<hostname>:<port>'
name: DC2
sync: true
operations:
- type: mirror
parameters:
queue_removal: false
```
Sample for sender-receiver operation:
```yaml
activemq_broker_connections:
- uri: 'tcp://<hostname>:<port>?<options>'
name: other-server
user: user
password: password
operations:
- type: sender
parameters:
address_match: 'queues.#'
- type: …
```

Fix `broker-connections` templating error, add missing parameters

---

molecule/custom_xml/converge.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml

Default value for the parameter `activemq_jvm_package` updated from `java-11-openjdk-headless` to `java-17-openjdk-headless`. 
If for any reason you need to continue using jdk11, and the parameter was not already present in the playbook/inventory, you now need to set it explicitly.
Closes #129

Update default jdk11 to jdk17

---

molecule/custom_xml/converge.yml
molecule/custom_xml/templates/test.properties
molecule/custom_xml/verify.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/configure_files.yml
roles/activemq/tasks/main.yml
roles/activemq/tasks/systemd.yml
roles/activemq/templates/amq_broker.sysconfig.j2

See: https://activemq.apache.org/components/artemis/documentation/latest/configuration-index.html#broker-properties
New parameter allows the configuration of the feature:
|`activemq_properties_file`| Properties file to allow updates and additions to the broker configuration after any xml has been parsed | `""` |
By default the new parameter will introduce no changes. If set to a file name, the role will search for a properties file with such name in the playbook default lookup locations (note: it cannot be template); the properties file will be copied to {{ instance.home }}/etc/ and added to the start up script arguments.

Allow to configure broker properties with properties file

---

README.md
molecule/default/verify.yml
molecule/mask_passwords/verify.yml
molecule/static_cluster/converge.yml
molecule/static_cluster/verify.yml
plugins/modules/activemq_facts.py

The new module calls into the jolokia API and returns activemq configuration / runtime info as Ansible facts.
Sample usage:
```yaml
- name: Populate activemq facts
middleware_automation.amq.activemq_facts:
base_url: http://0.0.0.0:8161
auth_username: ...
auth_password: ...
- name: Print activemq gathered facts
ansible.builtin.debug:
var: ansible_facts.activemq
```
returns:
```
TASK [debug] *******************************************************************
task path: /home/guido/Development/redhat/amq/molecule/default/verify.yml:15
ok: [instance] => {
"ansible_facts.activemq": {
"Acceptors": [
[
"artemis",
"org.apache.activemq.artemis.core.remoting.impl.netty.NettyAcceptorFactory",
{
"host": "localhost",
"port": "61616",
"protocols": "CORE,MQTT",
"scheme": "tcp",
"tcpReceiveBufferSize": …
```

Add fact gathering module for amq

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_artemis.yml
roles/activemq/templates/ha_policy.xml.j2

HA policy is set by the following parameters:
|`activemq_ha_enabled`| Whether to enable ha | `false` |
|`activemq_replication`| Enables replication | `false` |
|`activemq_replicated`| Designate instance as replicated node | `false` |
To designate nodes as replicas, use the `activemq_replicated` above in the node host_vars, or alternatively you can use
`activemq_ha_role` and assign to `primary` and `backup`

Add ha with replication policy

---

molecule/mask_passwords/converge.yml
molecule/mask_passwords/verify.yml
roles/activemq/tasks/mask_password.yml

Allow mixing masked and unmasked passwords

---

roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/main.yml
roles/activemq/tasks/systemd.yml

Refactor the systemd tasks file to allow executing as entrypoint (to add systemd control to already existing activemq deployments).
To execute: 
```yaml
- name: Install systemd unit for activemq service
ansible.builtin.include_role:
- name: activemq    
tasks_from: systemd
```
Refer to argument specs for the systemd entrypoint to see the reduced parameter list.

Define systemd entrypoint

---

molecule/default/converge.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_broker.yml
roles/activemq/tasks/network_check.yml
roles/activemq/tasks/validate_config.yml
roles/activemq/tasks/validate_network_check.yml
roles/activemq/vars/main.yml
roles/activemq_uninstall/defaults/main.yml

New parameters to configure network checks:
|`activemq_network_check_enabled`| Whether to enable network check | `false` |
|`activemq_network_check_period`| How often to check network reachability (ms) | `10000` |
|`activemq_network_check_timeout`| Connection timeout for network checks (ms) | `1000` |
|`activemq_network_check_list`| The addresses to use for checking; comma separated list, no spaces, just DNS or IPs | `''` |
|`activemq_network_check_NIC`| The network card to use for network checking | `''` |
|`activemq_network_check_ping_command`| The ping command to network check IPv4 | `''` |
|`activemq_network_check_ping6_command`|The ping command to network check IPv6 | `''` |
See: …

Add network check parameters

---

molecule/default/converge.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/vars/main.yml

New parameters to configure message counters:
|`activemq_message_counter_enabled`| Whether to enable the message counters | `false` |
|`activemq_message_counter_sample_period`| The sample period (in ms) to use for message counters| `10000` |
|`activemq_message_counter_max_day_history`| How many days to keep message counter history| `10` |

Allow to configure message counters

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/ha_policy.xml.j2

New parameters that apply to shared store or replication HA policies:
|`activemq_ha_allow_failback`| Whether a server will automatically stop when another places a request to take over its place |`true` |
|`activemq_ha_failover_on_shutdown`| Will this backup server become active on a normal server shutdown  | `true` |
|`activemq_ha_restart_backup`| Will this server, if a backup, restart once it has been stopped because of failback or scaling down | `false` |
|`activemq_ha_check_for_active_server`| Whether to check the cluster for a live server using our own server ID when starting up. This option is only necessary for performing 'fail-back' on replicating servers | `false` |
|`activemq_ha_replication_cluster_name`| …

Add additional ha-policy parameters

---

docs/systemd.md
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/amq_broker.service.j2

Make the port number and the matched string configurable for activemq_systemd_wait_for_xxx : 
|`activemq_systemd_wait_for_log_ha_string` | The string to match in the logs when `activemq_systemd_wait_for_log` is true and HA is enabled | `AMQ221109\|AMQ221001` |
|`activemq_systemd_wait_for_log_string` | The string to match in the logs when `activemq_systemd_wait_for_log` is true and HA is not enabled | `AMQ221034` |
|`activemq_systemd_wait_for_port_number`| The port number to wait for when `activemq_systemd_wait_for_port` is true | `{{ activemq_port }}` |
Also, the matched string in case of HA is not differentiated between primary and backup roles.

Add wait_for configuration

---

roles/activemq/tasks/configure_files.yml

Fix a regression caused by binding console to hostname in bootstrap.xml
Fix #157

Use bind_address instead of hostname for console binding

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/vars/main.yml

New parameters:
|`activemq_journal_buffer_size`| The size of the internal buffer on the journal in KB  | `490KiB` |
|`activemq_disk_scan_period`| The interval where the disk is scanned for percentual usage | `5000` |
|`activemq_max_disk_usage`| The max percentage of data we should use from disks. The System will block while the disk is full | `96` |

Add more journal configs

---

roles/activemq/README.md
roles/activemq/tasks/keystores.yml
roles/activemq/templates/amq_broker.sysconfig.j2

Fix the condition for transferring TLS stores, which would end in an error for paths defined as empty string.
This change also inverts nesting of single and double quotes in the sysconfig file for JAVA_ARGS: this allows to embed commands in it, like as follows:
-XX:HeapDumpPath=/varr/log/amq-broker/amq-broker_$(date "+%Y%m%d_%H%M%S").hprof

Fix condition for transferring key/trust store

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/configure_files.yml

The parameter allows to set an arbitrary value in the web console binding setting in `bootstrap.xml`.
```xml
<web path="web" rootRedirectLocation="console">
<binding name="artemis" uri="{{ activemq_console_bind_url }}">
```
`activemq_jolokia_url` and `activemq_console_url` are now re-defaulted to use such value.
|`activemq_jolokia_url`| URL for jolokia REST api | `{{ activemq_console_url }}/jolokia` |
|`activemq_console_url`| URL for console service | `{{ activemq_console_bind_url }}/console/` |
|`activemq_console_bind_url`| The value to use in bootstrap.xml for web console binding | `http{{ 's' if activemq_tls_enabled else '' }}://{{ activemq_bind_address }}:{{ activemq_http_port }}` |
No change to current …

New `activemq_console_bind_url` parameter

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/amq_broker.service.j2

When the new parameter is set to `true`:
|`activemq_systemd_expand_environment` | Whether or not to expand the environment in the sysconfig file. If true, environment file is sourced and the activemq process is started in a shell | `false` |
the systemd unit template is changed to run the activemq process in a shell, sourcing the sysconfig environment file just before exection. This allows to use shell expansions in the environment file.
Examples:
```yaml
activemq_systemd_expand_environment: true
activemq_java_opts_mem: '-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/amq_$(date "+%Y%m%d_%H%M%S").hprof'
```

Add `activemq_systemd_expand_environment` parameter

---

plugins/modules/activemq_facts.py

Instead of guessing the 'Origin' header value from the `base_url`, add a parameter for it. Defaults to `http:/0.0.0.0`.
```yaml
- name: Populate activemq facts
middleware_automation.amq.activemq_facts:
base_url: 'https://internal.access.jolokia'
auth_username: username
auth_password: password
web_origin: 'https://somesite.somedomain'
```
Corresponding CORS setting in the install role are:
|`activemq_cors_allow_origin`| List of CORS allow origin setting for jolokia | `[ *://0.0.0.0* ]` |
|`activemq_cors_strict_checking`| Whether to enforce strict checking for CORS | `True` |

Add `web_origin` parameter to `activemq_facts` module

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/tasks/connectors.yml
roles/activemq/tasks/main.yml
roles/activemq/templates/cluster_connections.broker.xml.j2
roles/activemq/templates/ha_policy.xml.j2

Add a new choice in `activemq_cluster_discovery`: `provided`, which leverages the new `activemq_cluster_connections` parameter to build the broker cluster-connections reusing the already defined `activemq_connectors` names.
|`activemq_cluster_discovery` | Cluster discovery: [`jgroups` (shared file ping), `multicast` (UDP), `static` (node list), `provided` (use `activemq_cluster_connections`)] | `static` |
|`activemq_cluster_connections`| The list of cluster connection names from the connectors list, when `activemq_cluster_discovery` = provided | `[]` |
When setting the new `provided` value, it is possible to define:
```yaml
activemq_connectors:
- name: master-AMQ01
scheme: tcp
address: amq01-primary.domain.tld
port: …
```

Allow to explicitly list `cluster-connections`

---

molecule/default/converge.yml
molecule/replication/converge.yml
roles/activemq/templates/addresses.broker.xml.j2
roles/activemq/templates/modular/addresses.xml.j2

Refactor `activemq_addresses` to behave in regards to parameters as `activemq_address_settings`, ie. each address iten in the list may have a `parameters` dict containing python-cased queue paramters.
```yaml
activemq_addresses:
- name: DLQ
anycast:
- name: DLQ
parameters:
durable: True
- name: client123.pubsub
multicast:
- name: client123.pubsub.foo
parameters:
max_consumers: 1
delay_before_dispatch: 3
```
Fix #169

Parameters for `activemq_addresses` as a dictionary

---

roles/activemq/tasks/configure_artemis.yml
roles/activemq/tasks/connectors.yml
roles/activemq/tasks/jgroups.yml

A regression was introduced by #168 when `activemq_cluster_discovery: provided`, which causes failure to start services because broadcast groups refers a non-existing connector.

Check broadcast/discovery groups absent with `provided` discovery

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml

The default for the parameter is updated to `AMQ221109\\\\|AMQ221001\\\\|AMQ221034`, in order to accomodate the scenario described in the linked issue.
Fix #185

Update default for `activemq_systemd_wait_for_log_ha_string`

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/log4j2.properties.j2
roles/activemq/templates/logging.properties.j2

|`activemq_logger_filepath` | Path for main logfile relative to instance directory | `/log/artemis.log` |

Add parameter `activemq_logger_filepath` to configure logfile path

---

roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/login.config.j2

New parameters to set roles in role expansion functionality allow to configure active directory as an ldap identity provider:
|`activemq_auth_ldap_expand_roles` | Whether to enable role expansion functionality; if enabled, then roles within roles will be found | `false` |
|`activemq_auth_ldap_expand_roles_matching` | An LDAP search filter which is applied to the subtree selected by roleBase | `(member={0})` |
Fix #188

Add role expansion parameters for ldap/AD configuration

---

roles/activemq/tasks/install.yml
roles/activemq/tasks/mask_password.yml

When mask passwords are generated via `artemis mask` command, the configured JDK is not used.
Refactor the blocks in the mark_passwords.yml taskfile to guard against undefined vars
Fix #196 
Fix #197

Fix password masking command JDK

---

.github/workflows/ci.yml
molecule/amq_upgrade/molecule.yml
molecule/custom_xml/molecule.yml
molecule/custom_xml/verify.yml
molecule/default/molecule.yml
molecule/mask_passwords/molecule.yml
molecule/requirements.yml
molecule/uninstall/molecule.yml
roles/activemq/tasks/install.yml

Workaround failed downloads for "error 101 - network unreachable". It only happened in CI till now, in rare cases when IPv6 is not available/not supported, but it is better to make it a main feature.

Update CI to have some podman self-hosted runners

---

galaxy.yml

There is only one functionnal change since 2.2.7 and its a minor fixes, thus making the next release a micro one.

Bump down version to 2.2.8

---

molecule/static_cluster/molecule.yml
roles/activemq/README.md
roles/activemq/defaults/main.yml
roles/activemq/meta/argument_specs.yml
roles/activemq/templates/ha_policy.xml.j2

The new role parameter allows to control failover-on-shutdown in backup instances, not to be confused with `activemq_ha_failover_on_shutdown`.
|`activemq_ha_failover_on_shutdown`| For a master broker, determines whether to fail over to a slave if it is shut down | `true` |
|`activemq_ha_backup_failover_on_shutdown`| For a slave broker, this element determines whether it becomes the master in case the master is shut down | `false` |
Fix #200

Add parameter `activemq_ha_backup_failover_on_shutdown`

---

roles/activemq/tasks/user_roles.yml

I am facing an error with the last change: "Destination /var/opt/amq-broker/amq-broker-7.12.1/schema not writable."
This is a PR to 'become' if needed.
The full AAP error:
```
Task: Make collection other xsd available for validation
Module: ansible.builtin.copy
```
```json
{
"msg": "Destination /var/opt/amq-broker/amq-broker-7.12.1/schema not writable",
"invocation": {
"module_args": {
"src": "/var/opt/amq-broker/amq-broker-7.12.1/schema/activemq.xsd",
"dest": "/var/opt/amq-broker/amq-broker-7.12.1/schema/amq_broker_fix.xsd",
"mode": "0644",
"remote_src": true,
"backup": false,
"force": true,
"follow": false,
"unsafe_writes": false,
"_original_basename": null,
"content": null,
"validate": null,
"directory_mode": null,
"local_follow": null,
"checksum": null,
"owner": null,
"group": null, …
```

fix amq-broker installer schema directory not writable

---

.github/workflows/ci.yml
molecule/schema_validation/converge.yml
molecule/schema_validation/files/activemq.xsd
molecule/schema_validation/molecule.yml
molecule/schema_validation/prepare.yml
roles/activemq/defaults/main.yml
roles/activemq/tasks/user_roles.yml

Issue: https://issues.redhat.com/browse/AMW-408

AMW--408 Error XMLSchemaParseError with Ansible collection 2.3.2 for AMQ 7.13
